# Generated by Django 6.0.2 on 2026-04-30 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_backfill_doctor_email_and_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='specialist_type',
            field=models.CharField(default='General Medicine', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='timings',
            field=models.TextField(default=''),
        ),
    ]
